export const EVENTS = {
    DOCUMENT_DELETED: 'DOCUMENT_DELETED',
    CONVERSATION_DELETED: 'CONVERSATION_DELETED',
    DATA_REFRESH_NEEDED: 'DATA_REFRESH_NEEDED',
    TITLE_UPDATED: 'TITLE_UPDATED'
};